###
POST https://api.goodjob.life/graphql HTTP/1.1
content-type: application/json

{
    "companyname": "廣達",
    
}

###
post http://localhost:5000/api/1.0/user/signup HTTP/1.1
ser-Agent: rest-client
Content-Type: application/json

{
    "nickname": "native",
    "email": "zoe77@gmail.com",
    "password":"123",
    "name":"zoe"
}
###

GET http://localhost:5000/api/1.0/chat HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTExMjM0NzMsImVtYWlsIjoiem9ldHc4OEBnbWFpbC5jb20iLCJuaWNrbmFtZSI6InpvZSIsImlhdCI6MTYwODEyMzQ3M30.GAxxrH_2F-RBUmXIXzGIlv0LKYZLCOKtIAveLyxTI3o

###

GET http://localhost:5000/api/1.0/salary?company=台灣積體電路製造股份有限公司&title=軟體工程師 HTTP/1.1
###

GET http://localhost:5000/api/1.0/workinghour?company=台達電子工業股份有限公司 HTTP/1.1

###
POST http://localhost:5000/get_main_messages
Content-Type: application/json

{
    "username":"zoe"
}

###

POST http://localhost:5000/get_select_messages
Content-Type: application/json

{
    "username":"zoe",
    "chosenName":"jeff"
}

###
POST http://localhost:5000/get_side_messages
Content-Type: application/json

{
 "username":"zoe"
    
}