


###
post http://localhost:5000/api/1.0/user/signup HTTP/1.1
ser-Agent: rest-client
Content-Type: application/json

{
    "nickname": "native",
    "email": "zoe77@gmail.com",
    "password":"123",
    "name":"zoe"
}
###

GET http://localhost:5000/api/1.0/chat HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTE2NDYwNzYsImVtYWlsIjoiem9lNzc4N3R3QGdtYWlsLmNvbSIsIm5pY2tuYW1lIjoiWk9F6ICB5aq9IiwiaWF0IjoxNjA4NjQ2MDc2fQ.dpcuHH79z8qJMR79ve14IhK942GKfGDf1BJxUyvIoaE

###

GET http://localhost:5000/api/1.0/salary?title=it&company=和碩 HTTP/1.1
###

GET http://localhost:5000/api/1.0/workinghour?company=&title=軟體 HTTP/1.1

###
POST http://localhost:5000/get_main_messages
Content-Type: application/json

{
    "username":"zoe"
}

###

POST http://localhost:5000/get_select_messages
Content-Type: application/json

{
    "username":"zoe",
    "chosenName":"jeff"
}

###
POST http://localhost:5000/get_side_messages
Content-Type: application/json

{
 "username":"zoe"
    
}

###
GET http://localhost:5000/api/1.0/comments?company=廣達&title=機構 HTTP/1.1

###
###
GET http://localhost:5000/api/1.0/keywords?company=廣達電腦股份有限公司&title= HTTP/1.1

###

GET http://localhost:5000/api/1.0/job104list?company=和碩聯合科技股份有限公司&title=軟體工程師 HTTP/1.1

###
POST http://localhost:5000/api/1.0/question
Content-Type: application/json

{
    "nickname":"10",
    "company":"廣達電腦股份有限公司",
    "question":"請問待遇如何"
}

###
###

GET http://localhost:5000/api/1.0/companylist
Content-Type: application/json

###
GET http://localhost:5000/api/1.0/job104list?company=廣達&title=廠務工程師
Content-Type: application/json